seed: 42

data:
  attr: "Smiling"
  image_size: 128
  batch_size: 128
  num_workers: 2

model:
  name: "resnet18"     # resnet18 or resnet50
  pretrained: true

train:
  epochs: 3
  lr: 0.0001
  optimizer: "adam"    # adam or sgd
  weight_decay: 0.0

paths:
  ckpt_name: "baseline_{attr}.pt"
